// Page-specific capability lane content, ported 1:1 from the old assets/js/app.js.
export const capabilitySets = {
  home: [
    ['Architecture', 'Cloud + Edge', 'modular by design'],
    ['Security', 'Zero-trust controls', 'built into delivery'],
    ['Delivery', 'PoC to scale', 'measurable gates'],
    ['Operations', 'Observable systems', 'SLIs and alerts'],
    ['AI/ML', 'Vision + RAG', 'decision intelligence'],
    ['Blockchain', 'Trusted records', 'auditable events'],
    ['Performance', 'Real-time speed', 'resilient data'],
    ['Software', 'Web + mobile', 'enterprise workflows'],
    ['Integration', 'API-first', 'legacy connected'],
    ['Field Apps', 'Offline-first', 'built for India'],
    ['Data', 'Governed pipelines', 'actionable dashboards'],
    ['Support', 'Runbooks + SLA', 'operational ownership'],
  ],
  ai: [
    ['Vision AI', 'Detect + classify', 'images and video'],
    ['Document AI', 'OCR + extraction', 'multilingual records'],
    ['RAG', 'Grounded answers', 'enterprise knowledge'],
    ['Predictive ML', 'Forecast + score', 'early decisions'],
    ['Anomaly AI', 'Detect risk', 'patterns at scale'],
    ['Recommendation', 'Personalise action', 'next-best outcome'],
    ['MLOps', 'Deploy safely', 'version and monitor'],
    ['Data Quality', 'Trusted inputs', 'validated pipelines'],
    ['Human Review', 'Confidence gates', 'responsible AI'],
    ['Edge AI', 'Low latency', 'field deployment'],
    ['Dashboards', 'Explain results', 'role-based views'],
    ['Integration', 'API services', 'existing systems'],
  ],
  blockchain: [
    ['Provenance', 'Track origin', 'signed events'],
    ['Certificates', 'Verify instantly', 'tamper evident'],
    ['Supply Chain', 'Lineage graph', 'end-to-end trust'],
    ['Audit Trail', 'Immutable proof', 'clear accountability'],
    ['Identity', 'Credential checks', 'permissioned access'],
    ['Smart Rules', 'Workflow logic', 'controlled actions'],
    ['Privacy', 'Selective sharing', 'need-to-know data'],
    ['Interoperability', 'API gateways', 'legacy integration'],
    ['Governance', 'Roles + policy', 'consortium controls'],
    ['Analytics', 'Ledger insight', 'risk and trace'],
    ['Recovery', 'Resilient nodes', 'operational continuity'],
    ['Scale', 'Batch + anchor', 'cost controlled'],
  ],
  affiliate: [
    ['Attribution', 'S2S postbacks', 'verified events'],
    ['Publishers', 'Curated network', 'source transparency'],
    ['Fraud', 'Pattern controls', 'protect payouts'],
    ['Creative', 'Rapid testing', 'fight fatigue'],
    ['Fintech', 'KYC + transaction', 'quality cohorts'],
    ['Commerce', 'Orders + returns', 'net revenue'],
    ['Gaming', 'Deposit + value', 'compliant growth'],
    ['OTT', 'Trial + renewal', 'retention view'],
    ['Reconciliation', 'Approve + dispute', 'evidence trail'],
    ['Reporting', 'Source dashboards', 'daily decisions'],
    ['Optimisation', 'Scale winners', 'cut leakage'],
    ['Global Reach', 'Multi-geo supply', 'local controls'],
  ],
  traceability: [
    ['Lineage', 'Origin to user', 'connected lots'],
    ['QR Verify', 'Instant scan', 'citizen confidence'],
    ['Offline App', 'Field ready', 'sync later'],
    ['AI Detection', 'Spot anomalies', 'risk prioritised'],
    ['Blockchain', 'Signed history', 'tamper evidence'],
    ['Recall', 'Find affected lots', 'faster action'],
    ['Inspector', 'Evidence capture', 'geo + time'],
    ['Manufacturer', 'Batch control', 'production events'],
    ['Distributor', 'Transfer proof', 'inventory trail'],
    ['Retail', 'Last-mile check', 'sale visibility'],
    ['Analytics', 'Heatmaps + alerts', 'operational insight'],
    ['API', 'Ecosystem link', 'government systems'],
  ],
  government: [
    ['Citizen UX', 'Accessible services', 'mobile first'],
    ['Department Ops', 'Role workflows', 'clear ownership'],
    ['DPI Integration', 'API-first', 'interoperable'],
    ['Security', 'By design', 'auditable controls'],
    ['Data', 'Governed records', 'single source'],
    ['Field Systems', 'Offline-first', 'low-connectivity'],
    ['Command View', 'Live dashboards', 'decision support'],
    ['Procurement', 'Milestone delivery', 'documented gates'],
    ['PoC', 'Measured pilot', 'before scale'],
    ['Training', 'Adoption support', 'role based'],
    ['SLA', 'Service levels', 'operational clarity'],
    ['Scale', 'State to national', 'modular growth'],
  ],
  default: [
    ['Architecture', 'Cloud + Edge', 'modular by design'],
    ['Security', 'By design', 'auditable controls'],
    ['Delivery', 'PoC to scale', 'measured outcomes'],
    ['Operations', 'Observable', 'stable systems'],
    ['Data', 'Governed', 'trusted insight'],
    ['Integration', 'API-first', 'connected systems'],
    ['Experience', 'Human-centred', 'usable software'],
    ['Performance', 'Fast + resilient', 'real-world load'],
    ['Field', 'Offline-first', 'India ready'],
    ['Automation', 'Workflow driven', 'less friction'],
    ['Support', 'Runbooks + SLA', 'accountable care'],
    ['Scale', 'Modular growth', 'future ready'],
  ],
}
