(()=>{const q=(s,c=document)=>c.querySelector(s),qa=(s,c=document)=>[...c.querySelectorAll(s)];addEventListener('load',()=>setTimeout(()=>q('#pageLoader')?.classList.add('done'),180));q('#year')&&(q('#year').textContent=new Date().getFullYear());const mt=q('#menuToggle'),nl=q('#navLinks');mt?.addEventListener('click',()=>{const o=nl.classList.toggle('open');mt.setAttribute('aria-expanded',String(o))});qa('.nav-links a').forEach(a=>a.addEventListener('click',()=>{if(innerWidth<981)nl?.classList.remove('open')}));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');const n=e.target.querySelector?.('[data-counter]');if(n&&!n.dataset.done){n.dataset.done=1;let t=0,target=+n.dataset.counter;const step=()=>{t+=Math.max(.1,target/30);n.textContent=Math.min(target,Math.floor(t));if(t<target)requestAnimationFrame(step)};step()}}}),{threshold:.12});qa('.section,.card,.metric,.band,.timeline-item,.usecase,.quote-panel,.check-card,.logo-wall span').forEach(el=>{el.classList.add('reveal');io.observe(el)});
const video=q('#bgVideo');video?.addEventListener('error',()=>document.body.classList.add('video-fallback'));document.addEventListener('visibilitychange',()=>{if(!video)return;document.hidden?video.pause():video.play().catch(()=>{})});if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
let mx=0,my=0;addEventListener('pointermove',e=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5;qa('.hud,.page-symbol').forEach((h,i)=>h.style.translate=`${mx*(i?8:16)}px ${my*(i?8:16)}px`)},{passive:true});
const c=q('#networkCanvas');if(!c)return;const x=c.getContext('2d');const mode=document.documentElement.dataset.page||'default';let w,h,dpr=Math.min(devicePixelRatio||1,2),pts=[],packets=[];const cfg={redis:{nodes:125,speed:.42,links:115,packet:28,accent:'220,74,74'},ai:{nodes:170,speed:.28,links:145,packet:20,accent:'216,179,79'},blockchain:{nodes:95,speed:.18,links:170,packet:12,accent:'214,202,160'},affiliate:{nodes:145,speed:.38,links:125,packet:24,accent:'216,179,79'},traceability:{nodes:110,speed:.22,links:155,packet:14,accent:'202,184,116'},contact:{nodes:70,speed:.12,links:125,packet:7,accent:'216,179,79'},default:{nodes:140,speed:.24,links:135,packet:16,accent:'216,179,79'}}[mode]||{nodes:140,speed:.24,links:135,packet:16,accent:'216,179,79'};
function resize(){w=innerWidth;h=innerHeight;c.width=w*dpr;c.height=h*dpr;c.style.width=w+'px';c.style.height=h+'px';x.setTransform(dpr,0,0,dpr,0,0);let n=Math.min(cfg.nodes,Math.floor(w*h/9000));pts=Array.from({length:n},(_,i)=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*cfg.speed,vy:(Math.random()-.5)*cfg.speed,r:Math.random()*1.4+.35,z:Math.random(),band:mode==='blockchain'?i%4:0}));packets=Array.from({length:cfg.packet},()=>({a:Math.floor(Math.random()*n),b:Math.floor(Math.random()*n),t:Math.random(),v:.002+Math.random()*.005}))}
function draw(){x.clearRect(0,0,w,h);for(const p of pts){p.x+=p.vx+mx*.04*(p.z+.2);p.y+=p.vy+my*.04*(p.z+.2);if(mode==='traceability')p.y+=.05;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;x.beginPath();x.fillStyle=`rgba(${cfg.accent},${.16+p.z*.46})`;if(mode==='blockchain'){x.rect(p.x-1.5,p.y-1.5,3+p.z*2,3+p.z*2)}else{x.arc(p.x,p.y,p.r+p.z*.8,0,Math.PI*2)}x.fill()}for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){const a=pts[i],b=pts[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<cfg.links&&(mode!=='blockchain'||a.band===b.band)){x.strokeStyle=`rgba(${cfg.accent},${(1-d/cfg.links)*.13})`;x.lineWidth=.45;x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.stroke()}}for(const p of packets){const a=pts[p.a],b=pts[p.b];if(!a||!b)continue;p.t+=p.v;if(p.t>1){p.t=0;p.a=p.b;p.b=Math.floor(Math.random()*pts.length)}const px=a.x+(b.x-a.x)*p.t,py=a.y+(b.y-a.y)*p.t;x.beginPath();x.fillStyle=`rgba(${cfg.accent},.95)`;x.shadowBlur=14;x.shadowColor=`rgb(${cfg.accent})`;x.arc(px,py,mode==='redis'?2.8:2.1,0,Math.PI*2);x.fill();x.shadowBlur=0}requestAnimationFrame(draw)}addEventListener('resize',resize,{passive:true});resize();draw()})();
;(()=>{
  const page=document.documentElement.dataset.page||'default';
  const sets={
    home:[['Architecture','Cloud + Edge','modular by design'],['Security','Zero-trust controls','built into delivery'],['Delivery','PoC to scale','measurable gates'],['Operations','Observable systems','SLIs and alerts'],['AI/ML','Vision + RAG','decision intelligence'],['Blockchain','Trusted records','auditable events'],['Redis','Real-time speed','resilient data'],['Software','Web + mobile','enterprise workflows'],['Integration','API-first','legacy connected'],['Field Apps','Offline-first','built for India'],['Data','Governed pipelines','actionable dashboards'],['Support','Runbooks + SLA','operational ownership']],
    ai:[['Vision AI','Detect + classify','images and video'],['Document AI','OCR + extraction','multilingual records'],['RAG','Grounded answers','enterprise knowledge'],['Predictive ML','Forecast + score','early decisions'],['Anomaly AI','Detect risk','patterns at scale'],['Recommendation','Personalise action','next-best outcome'],['MLOps','Deploy safely','version and monitor'],['Data Quality','Trusted inputs','validated pipelines'],['Human Review','Confidence gates','responsible AI'],['Edge AI','Low latency','field deployment'],['Dashboards','Explain results','role-based views'],['Integration','API services','existing systems']],
    blockchain:[['Provenance','Track origin','signed events'],['Certificates','Verify instantly','tamper evident'],['Supply Chain','Lineage graph','end-to-end trust'],['Audit Trail','Immutable proof','clear accountability'],['Identity','Credential checks','permissioned access'],['Smart Rules','Workflow logic','controlled actions'],['Privacy','Selective sharing','need-to-know data'],['Interoperability','API gateways','legacy integration'],['Governance','Roles + policy','consortium controls'],['Analytics','Ledger insight','risk and trace'],['Recovery','Resilient nodes','operational continuity'],['Scale','Batch + anchor','cost controlled']],
    redis:[['Cache','Fast responses','lower DB load'],['Sessions','Reliable state','high-traffic portals'],['Streams','Real-time events','operational data'],['Search','Instant retrieval','citizen services'],['Cluster','Horizontal scale','production ready'],['Replication','High availability','fault tolerance'],['Sentinel','Automated failover','resilient service'],['Security','TLS + ACL','policy aligned'],['Observability','Latency + memory','actionable alerts'],['PoC','Baseline + proof','measured benefit'],['Migration','Low-risk rollout','phased adoption'],['Support','Runbooks + SLA','stable operations']],
    affiliate:[['Attribution','S2S postbacks','verified events'],['Publishers','Curated network','source transparency'],['Fraud','Pattern controls','protect payouts'],['Creative','Rapid testing','fight fatigue'],['Fintech','KYC + transaction','quality cohorts'],['Commerce','Orders + returns','net revenue'],['Gaming','Deposit + value','compliant growth'],['OTT','Trial + renewal','retention view'],['Reconciliation','Approve + dispute','evidence trail'],['Reporting','Source dashboards','daily decisions'],['Optimisation','Scale winners','cut leakage'],['Global Reach','Multi-geo supply','local controls']],
    traceability:[['Lineage','Origin to user','connected lots'],['QR Verify','Instant scan','citizen confidence'],['Offline App','Field ready','sync later'],['AI Detection','Spot anomalies','risk prioritised'],['Blockchain','Signed history','tamper evidence'],['Recall','Find affected lots','faster action'],['Inspector','Evidence capture','geo + time'],['Manufacturer','Batch control','production events'],['Distributor','Transfer proof','inventory trail'],['Retail','Last-mile check','sale visibility'],['Analytics','Heatmaps + alerts','operational insight'],['API','Ecosystem link','government systems']],
    government:[['Citizen UX','Accessible services','mobile first'],['Department Ops','Role workflows','clear ownership'],['DPI Integration','API-first','interoperable'],['Security','By design','auditable controls'],['Data','Governed records','single source'],['Field Systems','Offline-first','low-connectivity'],['Command View','Live dashboards','decision support'],['Procurement','Milestone delivery','documented gates'],['PoC','Measured pilot','before scale'],['Training','Adoption support','role based'],['SLA','Service levels','operational clarity'],['Scale','State to national','modular growth']],
    default:[['Architecture','Cloud + Edge','modular by design'],['Security','By design','auditable controls'],['Delivery','PoC to scale','measured outcomes'],['Operations','Observable','stable systems'],['Data','Governed','trusted insight'],['Integration','API-first','connected systems'],['Experience','Human-centred','usable software'],['Performance','Fast + resilient','real-world load'],['Field','Offline-first','India ready'],['Automation','Workflow driven','less friction'],['Support','Runbooks + SLA','accountable care'],['Scale','Modular growth','future ready']]
  };
  const cards=sets[page]||sets.default;
  document.querySelectorAll('.capability-lane').forEach((lane,idx)=>{
    const ordered=idx?cards.slice().reverse():cards;
    const doubled=[...ordered,...ordered];
    lane.innerHTML=doubled.map(([a,b,c])=>`<div class="capability-card"><small>${a}</small><b>${b}</b><em>${c}</em></div>`).join('');
  });
})();

;(()=>{
 const orbit=document.getElementById('capabilityOrbit'),copy=document.getElementById('orbitCopy');
 const texts={build:['Build','Design and deliver modular enterprise platforms, citizen applications and data products with clear operating ownership.'],modernise:['Modernise','Replace fragile legacy experiences through APIs, phased migration and controlled change.'],scale:['Scale','Move from pilot to multi-region or national operation with capacity, training and support.'],optimise:['Optimise','Use telemetry, analytics and testing to improve cost, speed, reliability and adoption.'],secure:['Secure','Embed identity, access, audit, privacy, resilience and incident readiness into design.'],integrate:['Integrate','Connect legacy applications, registries, devices and partner systems through governed APIs.'],automate:['Automate','Remove repetitive work using workflow engines, AI assistance and event-driven processes.'],analyse:['Analyse','Turn operational data into dashboards, alerts, prediction and decision support.'],govern:['Govern','Define ownership, policy, approval, lineage and evidence across the platform.'],monitor:['Monitor','Observe service levels, latency, errors, security, business outcomes and user experience.']};
 orbit?.addEventListener('click',e=>{const b=e.target.closest('button[data-cap]');if(!b)return;orbit.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const [h,p]=texts[b.dataset.cap];copy.innerHTML=`<h3>${h}</h3><p>${p}</p>`;beep(520,.035)});
 const map=document.getElementById('architectureMap'),detail=document.getElementById('architectureDetail');map?.addEventListener('click',e=>{const b=e.target.closest('button[data-info]');if(b){detail.textContent=b.dataset.info;beep(620,.03)}});
 let audioOn=false,ctx;window.beep=(freq=440,d=.03)=>{if(!audioOn)return;ctx=ctx||new (window.AudioContext||window.webkitAudioContext)();const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;g.gain.value=.025;o.connect(g);g.connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+d);o.stop(ctx.currentTime+d)};
 const st=document.getElementById('soundToggle');st?.addEventListener('click',()=>{audioOn=!audioOn;st.textContent=audioOn?'Sound on':'Sound off';if(audioOn)beep(700,.05)});document.addEventListener('pointerover',e=>{if(e.target.closest('a,.btn,button'))beep(360,.018)},{passive:true});
 const launch=document.getElementById('aiLaunch'),panel=document.getElementById('aiPanel'),close=document.getElementById('aiClose'),form=document.getElementById('aiForm'),input=document.getElementById('aiInput'),msgs=document.getElementById('aiMessages');
 const answers={redis:'IRAH can structure a Redis PoC around a measurable workload, baseline latency and database load, then test caching, sessions, streams, resilience, security and operations before scale.',ai:'IRAH focuses on document AI, OCR, RAG, computer vision, prediction, anomaly detection, recommendation, multilingual assistants and MLOps.',government:'IRAH supports discovery, architecture, PoC, pilot, integration, training, SLA and scale for government and PSU programmes.',blockchain:'IRAH uses permissioned blockchain and signed provenance where tamper-evident history, verification and multi-party trust are justified.',affiliate:'IRAH combines publisher operations, server-side attribution, fraud controls, creative optimisation, reconciliation and cohort economics.',product:'IRAH product concepts include Bharat Food Assure and Seed Traceability, combining AI, field applications and provenance.',meeting:'Use the contact page to share your organisation, objective, project stage and timeline. IRAH will propose a focused next step.'};
 function reply(q){const s=q.toLowerCase();let a=answers.meeting;for(const k in answers)if(s.includes(k)){a=answers[k];break}msgs.insertAdjacentHTML('beforeend',`<div class="ai-bubble bot">${a}</div>`);msgs.scrollTop=msgs.scrollHeight}
 launch?.addEventListener('click',()=>{panel.classList.add('open');panel.setAttribute('aria-hidden','false')});close?.addEventListener('click',()=>{panel.classList.remove('open');panel.setAttribute('aria-hidden','true')});
 form?.addEventListener('submit',e=>{e.preventDefault();const q=input.value.trim();if(!q)return;msgs.insertAdjacentHTML('beforeend',`<div class="ai-bubble user">${q.replace(/[<>]/g,'')}</div>`);input.value='';setTimeout(()=>reply(q),250)});document.querySelectorAll('.ai-chips button').forEach(b=>b.addEventListener('click',()=>reply(b.textContent)));
})();


;(()=>{
 const explorer=document.getElementById('architectureExplorer'),panel=document.getElementById('architecturePanel');
 explorer?.addEventListener('click',e=>{const b=e.target.closest('button[data-title]');if(!b)return;explorer.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const tags=b.dataset.stack.split(' · ').map(x=>`<span>${x}</span>`).join('');panel.innerHTML=`<small>SELECTED LAYER</small><h3>${b.dataset.title}</h3><p>${b.dataset.copy}</p><div class="stack-tags">${tags}</div>`;beep(610,.03)});
 const detail=document.getElementById('buildDetail'),show=document.getElementById('buildShowcase');
 const build={1:['Discovery','Define the mandate, users, operating constraints, data reality, baseline performance and measurable success criteria.'],2:['Architecture','Design experience, integrations, data ownership, security, infrastructure, resilience and operating responsibilities.'],3:['Prototype','Validate the highest-risk assumptions quickly through working interaction and technical slices.'],4:['Proof of Concept','Measure technical and business evidence against agreed gates before production commitment.'],5:['Pilot','Use real users, real data and controlled scope to prove adoption, support and operational behaviour.'],6:['Scale','Plan migration, capacity, training, rollout waves, governance and service-level ownership.'],7:['Operate','Run the platform with observability, incident response, maintenance, support and accountable service levels.'],8:['Improve','Use product analytics, user feedback, operating evidence and roadmap governance for continuous improvement.']};
 show?.addEventListener('click',e=>{const b=e.target.closest('button[data-step]');if(!b)return;show.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const [h,p]=build[b.dataset.step];detail.innerHTML=`<h3>${h}</h3><p>${p}</p>`;beep(540,.03)});
 const stages=[...document.querySelectorAll('.wizard-stage')],wiz=document.getElementById('architectWizard'),result=document.getElementById('architectResult');let current=1,answers=[];
 wiz?.addEventListener('click',e=>{const b=e.target.closest('.wizard-options button');if(!b)return;answers.push(b.dataset.value);stages.find(x=>x.dataset.stage==current)?.classList.remove('active');current++;document.querySelectorAll('.wizard-progress span').forEach((s,i)=>s.classList.toggle('active',i<current));if(current<=4){stages.find(x=>x.dataset.stage==current)?.classList.add('active')}else{showResult()} });
 function showResult(){result.hidden=false;const [org,need,constraint,outcome]=answers;let title='Enterprise platform discovery',copy='A focused discovery should define users, workflows, data, constraints, architecture and measurable success gates before build.',stack=['Product discovery','Enterprise architecture','Security','Delivery governance'];if(need==='Performance'){title='Redis performance PoC';copy='Baseline one high-impact workload, design a safe Redis pattern, test resilience and measure latency plus database-load improvement before scale.';stack=['Redis','Observability','API integration','Failover testing']}else if(need==='AI'){title='Governed AI platform pilot';copy='Select one decision or document workflow, establish trusted data, deploy a human-reviewed AI service and measure accuracy, speed and adoption.';stack=['Document AI / RAG','MLOps','Human review','Analytics']}else if(need==='Trust'){title='Blockchain traceability pilot';copy='Define the event model, participating roles, verification flow and evidence requirements before introducing a permissioned trust ledger.';stack=['Provenance','Field app','QR verification','Permissioned ledger']}else if(need==='Portal'){title='Digital platform modernisation';copy='Create a modular experience and integration architecture, then validate one end-to-end citizen or departmental workflow.';stack=['Web & mobile','API gateway','Workflow','Command dashboard']}else if(need==='Growth'){title='Affiliate growth control system';copy='Define the validated outcome, instrument server-side attribution, onboard governed supply and scale by customer value rather than raw volume.';stack=['S2S attribution','Publisher ops','Fraud controls','Reconciliation']};document.getElementById('resultTitle').textContent=title;document.getElementById('resultCopy').textContent=`For ${org||'your organisation'}, prioritise ${constraint||'operating constraints'} and begin with a ${outcome||'measured first stage'}. ${copy}`;document.getElementById('resultStack').innerHTML=stack.map(x=>`<span>${x}</span>`).join('');document.getElementById('resultContact').href='contact.php?intent='+encodeURIComponent(need||'platform');result.scrollIntoView({behavior:'smooth',block:'center'})}
 document.getElementById('restartWizard')?.addEventListener('click',()=>{answers=[];current=1;result.hidden=true;stages.forEach(x=>x.classList.toggle('active',x.dataset.stage==='1'));document.querySelectorAll('.wizard-progress span').forEach((s,i)=>s.classList.toggle('active',i===0));wiz.scrollIntoView({behavior:'smooth'})});
 const searchData=[
 ['Platform overview','platform.php','Platform','Architecture, delivery, software, AI, Redis and trust systems.'],['Enterprise Software','services.php','Platform','Web, mobile, APIs, cloud, DevSecOps and data engineering.'],['AI/ML Engineering','ai-ml.php','Platform','Document AI, RAG, vision, prediction and MLOps.'],['Blockchain Platforms','blockchain.php','Platform','Provenance, credentials, audit and permissioned workflows.'],['Redis for Government','redis-government.php','Solution','Performance, caching, sessions, streams and resilience.'],['Government & PSU','government-solutions.php','Solution','Citizen services, departmental platforms and field systems.'],['Affiliate Growth','affiliate-marketing.php','Solution','Attribution, partners, fraud controls and reconciliation.'],['Industries','industries.php','Solution','Education, agriculture, healthcare, utilities and more.'],['Bharat Food Assure','bharat-food-assure.php','Product','AI and blockchain-enabled food traceability concept.'],['Seed Traceability','seed-traceability.php','Product','Lineage from breeder to farmer with field verification.'],['Redis case framework','case-redis-government.php','Work','Measured PoC, security, operations and scale.'],['Affiliate scale case','case-affiliate-scale.php','Work','Partner quality, attribution, fraud and value cohorts.'],['Downloads','downloads.php','Resource','Enterprise, AI, Redis and affiliate briefs.'],['IRAH Labs','irah-labs.php','Resource','Research, prototypes and reference implementations.'],['Careers','careers.php','Company','Join teams building complex digital platforms.'],['Contact','contact.php','Company','Start a project conversation.']
 ];const input=document.getElementById('siteSearchInput'),results=document.getElementById('searchResults');function renderSearch(q=''){const s=q.trim().toLowerCase();const list=s?searchData.filter(x=>x.join(' ').toLowerCase().includes(s)):searchData;results.innerHTML=list.map(x=>`<a class="search-result" href="${x[1]}"><small>${x[2]}</small><h3>${x[0]}</h3><p>${x[3]}</p></a>`).join('')||'<div class="card">No matching pages. Try Redis, AI, government, blockchain or affiliate.</div>'}if(input){renderSearch();input.addEventListener('input',()=>renderSearch(input.value))}
})();
