<?php
if(session_status()===PHP_SESSION_NONE) session_start();
$error=''; $sent=false; $vals=['name'=>'','email'=>'','organisation'=>'','role'=>'','intent'=>$_GET['intent']??'','stage'=>'','timeline'=>'','budget'=>'','message'=>''];
if($_SERVER['REQUEST_METHOD']==='POST'){
 foreach($vals as $k=>$v){$vals[$k]=trim($_POST[$k]??'');}
 $hp=trim($_POST['website']??''); $csrf=$_POST['csrf']??'';
 if($hp){echo 'OK';exit;} elseif(!$csrf||!hash_equals($_SESSION['csrf']??'',$csrf)){$error='Session expired. Please reload and try again.';} elseif(strlen($vals['name'])<2){$error='Please enter your full name.';} elseif(!filter_var($vals['email'],FILTER_VALIDATE_EMAIL)){$error='Please enter a valid email.';} elseif(!$vals['intent']){$error='Please select the conversation type.';} elseif(strlen($vals['message'])<20){$error='Please add a little more detail.';} else {
  $to='contact@irahsolution.com';$subject='New IRAH enquiry - '.$vals['intent'];$body='';foreach($vals as $k=>$v)$body.=ucwords(str_replace('_',' ',$k)).": $v
";
  $headers='From: noreply@irahsolution.com
Reply-To: '.$vals['email'].'
';
  if(@mail($to,$subject,$body,$headers)){header('Location: thank-you.php');exit;} else {$error='We could not send the message. Please email contact@irahsolution.com.';}
 }
}
$_SESSION['csrf']=bin2hex(random_bytes(16));$csrf=$_SESSION['csrf'];
$pageTitle='Contact IRAH Solution';$pageDescription='Discuss enterprise software, AI, Redis, blockchain or affiliate growth with IRAH Solution.';$pageKey='contact';include 'includes/header.php';?>
<section class="hero hero-inner contact-hero"><div class="container narrow"><span class="eyebrow">Start a focused conversation</span><h1 class="gradient">Tell us the problem.<br>We’ll shape the next step.</h1><p>Share the department, application, workflow or campaign challenge. We usually respond within one to two business days.</p></div></section>
<section class="section"><div class="container contact-layout"><aside class="contact-aside"><h2>What happens next</h2><ol class="number-list"><li>We review your objective and constraints.</li><li>We identify the right discovery, PoC or campaign path.</li><li>We propose a focused working session and requested inputs.</li></ol><div class="contact-direct"><b>Direct contact</b><a href="mailto:contact@irahsolution.com">contact@irahsolution.com</a></div></aside><form class="contact-form enterprise-form" method="post" novalidate><input type="hidden" name="csrf" value="<?=htmlspecialchars($csrf)?>"><input class="hp" name="website" tabindex="-1" autocomplete="off"><?php if($error):?><div class="form-alert"><?=htmlspecialchars($error)?></div><?php endif;?><div class="form-grid"><label><span>Full name *</span><input name="name" value="<?=htmlspecialchars($vals['name'])?>" required></label><label><span>Work email *</span><input type="email" name="email" value="<?=htmlspecialchars($vals['email'])?>" required></label><label><span>Organisation</span><input name="organisation" value="<?=htmlspecialchars($vals['organisation'])?>"></label><label><span>Role / designation</span><input name="role" value="<?=htmlspecialchars($vals['role'])?>"></label><label><span>Conversation type *</span><select name="intent" required><option value="">Select</option><?php foreach(['redis'=>'Redis PoC','ai'=>'AI/ML platform','software'=>'Enterprise software','blockchain'=>'Blockchain / traceability','government'=>'Government / PSU programme','affiliate'=>'Affiliate growth','other'=>'Other'] as $v=>$n):?><option value="<?=$v?>" <?=$vals['intent']===$v?'selected':''?>><?=$n?></option><?php endforeach;?></select></label><label><span>Project stage</span><select name="stage"><option value="">Select</option><option>Exploring</option><option>Requirements defined</option><option>PoC planned</option><option>Tender / procurement</option><option>Existing system modernisation</option></select></label><label><span>Expected timeline</span><select name="timeline"><option value="">Select</option><option>Immediate</option><option>1-3 months</option><option>3-6 months</option><option>6-12 months</option><option>Planning only</option></select></label><label><span>Indicative budget</span><select name="budget"><option value="">Prefer not to say</option><option>Under ₹25 lakh</option><option>₹25 lakh - ₹1 crore</option><option>₹1 crore - ₹5 crore</option><option>Above ₹5 crore</option><option>To be determined</option></select></label><label class="full"><span>What are you trying to achieve? *</span><textarea name="message" rows="7" required><?=htmlspecialchars($vals['message'])?></textarea></label></div><div class="form-submit"><button class="btn btn-primary" type="submit">Send enquiry</button><p>By submitting, you agree that IRAH may contact you about this enquiry.</p></div></form></div></section><?php include 'includes/footer.php';?>